### ISSUE TITLE
dev-server is broken without webpack@4.19.0

### ISSUE THREAD

**Issue by EchoLynx** [bacher09/pwgen-for-bios#57]
Here's the error produced when the dev-server is run with the latest webpack (4.28.2 at time of writing):
```

$ npm run dev-server

> pwgen-for-bios@2.0.0 dev-server /home/user/pwgen-for-bios
> webpack-dev-server

/home/user/pwgen-for-bios/node_modules/webpack-cli/bin/config-yargs.js:89
                                describe: optionsSchema.definitions.output.properties.path.description,
                                                                           ^

TypeError: Cannot read property 'properties' of undefined
    at module.exports (/home/user/pwgen-for-bios/node_modules/webpack-cli/bin/config-yargs.js:89:48)
    at Object.<anonymous> (/home/user/pwgen-for-bios/node_modules/webpack-dev-server/bin/webpack-dev-server.js:84:40)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pwgen-for-bios@2.0.0 dev-server: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pwgen-for-bios@2.0.0 dev-server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-12-29T00_14_34_047Z-debug.log
```
Downgrading to webpack version 4.19.0 fixes this.
tl;dr:
```
npm install webpack@4.19.0
```
full output:
```
$ npm install webpack@4.19.0
npm WARN karma-webpack@3.0.5 requires a peer of webpack@^2.0.0 || ^3.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ webpack@4.19.0
added 4 packages from 4 contributors, removed 20 packages, updated 19 packages, moved 1 package and audited 22183 packages in 24.201s
found 11 vulnerabilities (2 low, 5 moderate, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details


$ npm run dev-server

> pwgen-for-bios@2.0.0 dev-server /home/user/pwgen-for-bios
> webpack-dev-server

clean-webpack-plugin: /home/user/pwgen-for-bios/dist has been removed.
ℹ ｢wds｣: Project is running at http://localhost:9000/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /home/user/pwgen-for-bios/dist
ℹ ｢wdm｣: Hash: 9f65541e4c93f43091fb
Version: webpack 4.19.0
Time: 2077ms
Built at: 12/28/2018 7:19:41 PM
                                    Asset      Size  Chunks             Chunk Names
    assets/bundle.9f65541e4c93f43091fb.js   426 KiB    main  [emitted]  main
assets/bundle.9f65541e4c93f43091fb.js.map   540 KiB    main  [emitted]  main
                 assets/bootstrap.min.css  46.6 KiB          [emitted]
                               index.html  4.21 KiB          [emitted]
Entrypoint main = assets/bundle.9f65541e4c93f43091fb.js assets/bundle.9f65541e4c93f43091fb.js.map
[0] multi (webpack)-dev-server/client?http://localhost:9000 ./src/ui.ts 40 bytes {main} [built]
[./node_modules/ansi-html/index.js] 4.16 KiB {main} [built]
[./node_modules/ansi-regex/index.js] 135 bytes {main} [built]
[./node_modules/events/events.js] 8.13 KiB {main} [built]
[./node_modules/loglevel/lib/loglevel.js] 7.68 KiB {main} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {main} [built]
[./node_modules/url/url.js] 22.8 KiB {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:9000] (webpack)-dev-server/client?http://localhost:9000 7.78 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.58 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {main} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 77 bytes {main} [built]
[./src/googleAnalytics.ts] 788 bytes {main} [built]
[./src/keygen/index.ts] 1.5 KiB {main} [built]
[./src/ui.ts] 2.51 KiB {main} [built]
    + 27 hidden modules
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./html/index.html] 5.04 KiB {0} [built]
    [./node_modules/html-webpack-plugin/node_modules/lodash/lodash.js] 527 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 509 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 519 bytes {0} [built]
ℹ ｢wdm｣: Compiled successfully.
^C

$
```

**Comment by bacher09** [comment]
Fixed in master.
